version: "2"

services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:0.1.1
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
    ports:
      - "8161:8161"
      - "61616:61616"
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

#docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.9-management

#docker run -e AMQ_USER=admin -e AMQ_PASSWORD=admin -p 8161:8161 -p 61616:61616 --name artemis quay.io/artemiscloud/activemq-artemis-broker:0.1.1